"""make_pt_subscription_start_date_nullable

Revision ID: 105dd56f6e3b
Revises: fd246fcb2495
Create Date: 2025-12-21 18:02:20.715616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '105dd56f6e3b'
down_revision = 'fd246fcb2495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_plan', schema=None) as batch_op:
        batch_op.alter_column('pt_subscription_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_plan', schema=None) as batch_op:
        batch_op.alter_column('pt_subscription_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
