"""add avatar_url to user

Revision ID: 3654940eda12
Revises: dffa5b16ecad
Create Date: 2025-11-28 16:19:28.325833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3654940eda12'
down_revision = 'dffa5b16ecad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_plan', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('training_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
