"""Add payment gateway fields

Revision ID: 446d2c34698b
Revises: dffa5b16ecad
Create Date: 2025-12-17 22:33:06.400710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446d2c34698b'
down_revision = 'dffa5b16ecad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('gateway', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('txn_ref', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('raw_response', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['txn_ref'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('raw_response')
        batch_op.drop_column('paid_at')
        batch_op.drop_column('txn_ref')
        batch_op.drop_column('gateway')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
