"""add package_type to gym_package

Revision ID: 4fbefcae88e4
Revises: 41af4cec7ee0
Create Date: 2025-12-19 22:19:30.241535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fbefcae88e4'
down_revision = '41af4cec7ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_type', sa.String(length=20), nullable=True))

    with op.batch_alter_table('training_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_plan', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    with op.batch_alter_table('gym_package', schema=None) as batch_op:
        batch_op.drop_column('package_type')

    # ### end Alembic commands ###
