"""empty message

Revision ID: df1d2b06f472
Revises: fd37e37c5260
Create Date: 2025-11-04 23:55:57.469053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df1d2b06f472'
down_revision = 'fd37e37c5260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))

    # ### end Alembic commands ###
