"""Remove full_name and birth_year from User, add first_name, last_name, birth_day

Revision ID: dffa5b16ecad
Revises: df1d2b06f472
Create Date: 2025-11-05 00:59:12.132710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dffa5b16ecad'
down_revision = 'df1d2b06f472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('birth_day', sa.Date(), nullable=True))
        batch_op.drop_column('full_name')
        batch_op.drop_column('birth_year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_year', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('full_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120), nullable=True))
        batch_op.drop_column('birth_day')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
