"""Remove gateway field from payment

Revision ID: f3f2269dfb5a
Revises: 446d2c34698b
Create Date: 2025-12-19 01:13:16.019672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3f2269dfb5a'
down_revision = '446d2c34698b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('gateway')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gateway', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))

    # ### end Alembic commands ###
