"""refactor_pt_to_pt_subscription_and_pt_package

Revision ID: fd246fcb2495
Revises: b2c3d4e5f6a7
Create Date: 2025-12-21 16:44:23.109802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = 'fd246fcb2495'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def table_exists(table_name):
    """Check if a table exists"""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Chỉ tạo bảng nếu chưa tồn tại
    if not table_exists('pt_package'):
        op.create_table('pt_package',
            sa.Column('name', sa.String(length=50), nullable=False),
            sa.Column('duration_months', sa.Integer(), nullable=False),
            sa.Column('price', sa.Float(), nullable=False),
            sa.Column('description', sa.String(length=255), nullable=True),
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
    
    if not table_exists('pt_subscription'):
        op.create_table('pt_subscription',
            sa.Column('member_id', sa.Integer(), nullable=False),
            sa.Column('pt_package_id', sa.Integer(), nullable=False),
            sa.Column('trainer_id', sa.Integer(), nullable=True),
            sa.Column('start_date', sa.DateTime(), nullable=True),
            sa.Column('end_date', sa.DateTime(), nullable=True),
            sa.Column('active', sa.Boolean(), nullable=True),
            sa.Column('status', sa.String(length=20), nullable=True),
            sa.Column('notes', sa.Text(), nullable=True),
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
            sa.ForeignKeyConstraint(['pt_package_id'], ['pt_package.id'], ),
            sa.ForeignKeyConstraint(['trainer_id'], ['trainer.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    
    # Xóa pt_request nếu tồn tại
    if table_exists('pt_request'):
        op.drop_table('pt_request')
    # Xóa cột package_type nếu tồn tại
    bind = op.get_bind()
    inspector = inspect(bind)
    if 'gym_package' in inspector.get_table_names():
        columns = [col['name'] for col in inspector.get_columns('gym_package')]
        if 'package_type' in columns:
            with op.batch_alter_table('gym_package', schema=None) as batch_op:
                batch_op.drop_column('package_type')

    # Xử lý training_plan
    if 'training_plan' in inspector.get_table_names():
        # Xóa các training_plan cũ (không có pt_subscription)
        op.execute("DELETE FROM training_plan")
        
        # Kiểm tra cột đã tồn tại chưa
        columns = [col['name'] for col in inspector.get_columns('training_plan')]
        need_add_column = 'pt_subscription_id' not in columns
        
        with op.batch_alter_table('training_plan', schema=None) as batch_op:
            # Thêm cột pt_subscription_id nếu chưa có
            if need_add_column:
                batch_op.add_column(sa.Column('pt_subscription_id', sa.Integer(), nullable=False))
            
            # Xóa cột date_created nếu tồn tại
            if 'date_created' in columns:
                batch_op.drop_column('date_created')
        
        # Tạo foreign key nếu chưa có (sau khi đã thêm cột)
        if need_add_column or 'pt_subscription_id' in columns:
            # Refresh inspector để lấy foreign keys mới nhất
            inspector = inspect(op.get_bind())
            fk_constraints = inspector.get_foreign_keys('training_plan')
            has_pt_subscription_fk = any(
                fk.get('referred_table') == 'pt_subscription' 
                for fk in fk_constraints
            )
            if not has_pt_subscription_fk:
                with op.batch_alter_table('training_plan', schema=None) as batch_op:
                    batch_op.create_foreign_key(None, 'pt_subscription', ['pt_subscription_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pt_subscription_id')

    with op.batch_alter_table('gym_package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))

    op.create_table('pt_request',
    sa.Column('member_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trainer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('membership_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], name=op.f('pt_request_ibfk_1')),
    sa.ForeignKeyConstraint(['membership_id'], ['membership.id'], name=op.f('pt_request_ibfk_2')),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainer.id'], name=op.f('pt_request_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('pt_subscription')
    op.drop_table('pt_package')
    # ### end Alembic commands ###
